<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2SIT919R2"><DocLocation><![CDATA[C:\Advanced Sales\Automation\Test Scripts\Recycle_TC_03]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Recycle_TC_03]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="833" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[4/28/2021 - 3:31:56]]></Time>
<TimeTick>1619577116</TimeTick>
<NodeArgs eType="Replay" icon="836" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[4/28/2021 - 3:31:57]]></Time>
<TimeTick>1619577117</TimeTick>
<NodeArgs eType="Replay" icon="836" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:01]]></Time>
<TimeTick>1619577121</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Main Menu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:01]]></Time>
<TimeTick>1619577121</TimeTick>
<NodeArgs eType="Replay" icon="838" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Main Menu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:03]]></Time>
<TimeTick>1619577123</TimeTick>
<NodeArgs eType="Replay" icon="839" nRep="14" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:03]]></Time>
<TimeTick>1619577123</TimeTick>
<NodeArgs eType="Replay" icon="839" nRep="15" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:03]]></Time>
<TimeTick>1619577123</TimeTick>
<NodeArgs eType="Replay" icon="839" nRep="17" >
<Disp><![CDATA[Back Office.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:03]]></Time>
<TimeTick>1619577123</TimeTick>
<NodeArgs eType="Replay" icon="840" nRep="19" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:03]]></Time>
<TimeTick>1619577123</TimeTick>
<NodeArgs eType="Replay" icon="840" nRep="21" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Back Office Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fad465bbaab8ecd3c73e570d644"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:04]]></Time>
<TimeTick>1619577124</TimeTick>
<NodeArgs eType="Replay" icon="840" nRep="23" >
<Disp><![CDATA[Back Office Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:04]]></Time>
<TimeTick>1619577124</TimeTick>
<NodeArgs eType="Replay" icon="840" nRep="25" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:09]]></Time>
<TimeTick>1619577129</TimeTick>
<NodeArgs eType="Replay" icon="839" nRep="27" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:11]]></Time>
<TimeTick>1619577131</TimeTick>
<NodeArgs eType="Replay" icon="839" nRep="28" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:11]]></Time>
<TimeTick>1619577131</TimeTick>
<NodeArgs eType="Replay" icon="839" nRep="30" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:15]]></Time>
<TimeTick>1619577135</TimeTick>
<NodeArgs eType="Replay" icon="839" nRep="32" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[DtvList.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#2"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:36]]></Time>
<TimeTick>1619577156</TimeTick>
<NodeArgs eType="Replay" icon="838" nRep="35" status="Warning" >
<Disp><![CDATA[DtvList.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[DtvList]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"DtvList"&nbsp;(of&nbsp;class&nbsp;JavaList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:36]]></Time>
<TimeTick>1619577156</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[DtvList]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Toolkit Class = dtv.ui.swing.DtvList<br>to_class = JavaList<br>Index = 0<br>]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:36]]></Time>
<TimeTick>1619577156</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="38" status="Warning" nType="Description" >
<Disp><![CDATA[DtvList]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="838" nRep="37" status="Failed" nType="Run Error" >
<Disp><![CDATA[DtvList]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="837" nRep="11" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:36]]></Time>
<TimeTick>1619577156</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;DtvList&quot; (of class JavaList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Advanced Sales\Automation\Function Library\Recycle.qfl<BR/>Line (461): &quot;JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaList(&quot;DtvList&quot;).Select &quot;#2&quot;&quot;.]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:36]]></Time>
<TimeTick>1619577156</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="40" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="460" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[DtvList.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#6"]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:59]]></Time>
<TimeTick>1619577179</TimeTick>
<NodeArgs eType="Replay" icon="838" nRep="43" status="Warning" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[DtvList.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[DtvList]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"DtvList"&nbsp;(of&nbsp;class&nbsp;JavaList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:59]]></Time>
<TimeTick>1619577179</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[DtvList]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Toolkit Class = dtv.ui.swing.DtvList<br>to_class = JavaList<br>Index = 0<br>]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:59]]></Time>
<TimeTick>1619577179</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="46" status="Warning" nType="Description" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[DtvList]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="838" nRep="45" status="Failed" nType="Run Error" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[DtvList]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="837" nRep="39" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:59]]></Time>
<TimeTick>1619577179</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;DtvList&quot; (of class JavaList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Advanced Sales\Automation\Function Library\Recycle.qfl<BR/>Line (463): &quot;JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaList(&quot;DtvList&quot;).Select &quot;#6&quot;&quot;.]]></Details>
<Time><![CDATA[4/28/2021 - 3:32:59]]></Time>
<TimeTick>1619577179</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="48" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="462" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Adjustment Type.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Sellable"]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:22]]></Time>
<TimeTick>1619577202</TimeTick>
<NodeArgs eType="Replay" icon="838" nRep="51" status="Warning" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Adjustment Type.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Adjustment Type]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Adjustment&nbsp;Type"&nbsp;(of&nbsp;class&nbsp;JavaList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:22]]></Time>
<TimeTick>1619577202</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Adjustment Type]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaList<br>Attached Text = Adjustment Type<br>]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:22]]></Time>
<TimeTick>1619577202</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="54" status="Warning" nType="Description" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Adjustment Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="838" nRep="53" status="Failed" nType="Run Error" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Adjustment Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="837" nRep="47" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:22]]></Time>
<TimeTick>1619577202</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Adjustment Type&quot; (of class JavaList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Advanced Sales\Automation\Function Library\Recycle.qfl<BR/>Line (465): &quot;JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaList(&quot;Adjustment Type&quot;).Select &quot;Sellable&quot;&quot;.]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:22]]></Time>
<TimeTick>1619577202</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="56" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="464" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Reason.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["BUNDLE CREATE"]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:44]]></Time>
<TimeTick>1619577224</TimeTick>
<NodeArgs eType="Replay" icon="838" nRep="59" status="Warning" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Reason.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Reason]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Reason"&nbsp;(of&nbsp;class&nbsp;JavaList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:44]]></Time>
<TimeTick>1619577224</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Reason]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaList<br>Attached Text = Reason<br>]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:44]]></Time>
<TimeTick>1619577224</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="62" status="Warning" nType="Description" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Reason]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="838" nRep="61" status="Failed" nType="Run Error" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Reason]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="837" nRep="55" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:44]]></Time>
<TimeTick>1619577224</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Reason&quot; (of class JavaList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Advanced Sales\Automation\Function Library\Recycle.qfl<BR/>Line (467): &quot;JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaList(&quot;Reason&quot;).Select &quot;BUNDLE CREATE&quot;&quot;.]]></Details>
<Time><![CDATA[4/28/2021 - 3:33:44]]></Time>
<TimeTick>1619577224</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="64" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="466" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Justification.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TESTING"]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:07]]></Time>
<TimeTick>1619577247</TimeTick>
<NodeArgs eType="Replay" icon="840" nRep="67" status="Warning" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Justification.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Justification]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Justification"&nbsp;(of&nbsp;class&nbsp;JavaEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:07]]></Time>
<TimeTick>1619577247</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Justification]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaEdit<br>Attached Text = Justification<br>]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:07]]></Time>
<TimeTick>1619577247</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="70" status="Warning" nType="Description" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Justification]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="840" nRep="69" status="Failed" nType="Run Error" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Justification]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="837" nRep="63" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:07]]></Time>
<TimeTick>1619577247</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Justification&quot; (of class JavaEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Advanced Sales\Automation\Function Library\Recycle.qfl<BR/>Line (469): &quot;JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaEdit(&quot;Justification&quot;).Set &quot;TESTING&quot;&quot;.]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:07]]></Time>
<TimeTick>1619577247</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="72" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="468" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:29]]></Time>
<TimeTick>1619577269</TimeTick>
<NodeArgs eType="Replay" icon="839" nRep="75" status="Warning" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Confirm]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Confirm"&nbsp;(of&nbsp;class&nbsp;JavaButton).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:29]]></Time>
<TimeTick>1619577269</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Confirm]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Toolkit Class = dtv.ui.swing.DtvButton<br>to_class = JavaButton<br>Label = Confirm<br>Index = 1<br>Attached Text = Confirm<br>]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:29]]></Time>
<TimeTick>1619577269</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="78" status="Warning" nType="Description" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Confirm]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="839" nRep="77" status="Failed" nType="Run Error" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Confirm]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="837" nRep="71" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:29]]></Time>
<TimeTick>1619577269</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Confirm&quot; (of class JavaButton).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: C:\Advanced Sales\Automation\Function Library\Recycle.qfl<BR/>Line (471): &quot;JavaWindow(&quot;Oracle Retail Xstore Point&quot;).JavaButton(&quot;Confirm&quot;).Click&quot;.]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:29]]></Time>
<TimeTick>1619577269</TimeTick>
<NodeArgs eType="Replay" icon="841" nRep="80" status="Failed" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="470" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[1]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Enter PLU.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6901443275137"]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:52]]></Time>
<TimeTick>1619577292</TimeTick>
<NodeArgs eType="Replay" icon="840" nRep="83" status="Warning" Source="C:\Advanced Sales\Automation\Function Library\Recycle.qfl" SourceLine="-1" >
<Disp><![CDATA[Enter PLU.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Enter PLU]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Enter&nbsp;PLU"&nbsp;(of&nbsp;class&nbsp;JavaEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:52]]></Time>
<TimeTick>1619577292</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Enter PLU]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaEdit<br>Attached Text = Enter PLU<br>]]></Details>
<Time><![CDATA[4/28/2021 - 3:34:52]]></Time>
<TimeTick>1619577292</TimeTick>