<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2SIT919R2"><DocLocation><![CDATA[C:\Advanced Sales\Automation\Test Scripts\Repairs_Reg_06_8_RepairTable]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Repairs_Reg_06_8_RepairTable]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="480" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
Flex.]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:20]]></Time>
<TimeTick>1619583620</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:24]]></Time>
<TimeTick>1619583624</TimeTick>
<NodeArgs eType="Replay" icon="483" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:24]]></Time>
<TimeTick>1619583624</TimeTick>
<NodeArgs eType="Replay" icon="483" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:28]]></Time>
<TimeTick>1619583628</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Main Menu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:28]]></Time>
<TimeTick>1619583628</TimeTick>
<NodeArgs eType="Replay" icon="485" nRep="13" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Main Menu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:31]]></Time>
<TimeTick>1619583631</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="15" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Till.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:33]]></Time>
<TimeTick>1619583633</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="17" >
<Disp><![CDATA[Till.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:36]]></Time>
<TimeTick>1619583636</TimeTick>
<NodeArgs eType="Replay" icon="487" nRep="19" >
<Disp><![CDATA[Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:36]]></Time>
<TimeTick>1619583636</TimeTick>
<NodeArgs eType="Replay" icon="487" nRep="21" >
<Disp><![CDATA[Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["1234"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:38]]></Time>
<TimeTick>1619583638</TimeTick>
<NodeArgs eType="Replay" icon="487" nRep="23" >
<Disp><![CDATA[Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:38]]></Time>
<TimeTick>1619583638</TimeTick>
<NodeArgs eType="Replay" icon="487" nRep="25" >
<Disp><![CDATA[Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:45]]></Time>
<TimeTick>1619583645</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="27" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:49]]></Time>
<TimeTick>1619583649</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="29" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:53]]></Time>
<TimeTick>1619583653</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="31" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Additional Options.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:56]]></Time>
<TimeTick>1619583656</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="33" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Additional Options.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Repair Payment.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:58]]></Time>
<TimeTick>1619583658</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="34" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Repair Payment.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="484" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[The repair button is present]]></Obj>
<Details ><![CDATA[Test case passed]]></Details>
<Time><![CDATA[4/28/2021 - 5:20:58]]></Time>
<TimeTick>1619583658</TimeTick>
<NodeArgs eType="User" icon="488" nRep="35" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[The repair button is present]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:02]]></Time>
<TimeTick>1619583662</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Repair Payment.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:02]]></Time>
<TimeTick>1619583662</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="38" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Repair Payment.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Retrieve.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:04]]></Time>
<TimeTick>1619583664</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="40" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Retrieve.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="484" nRep="37" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[No Pending transactions exists]]></Obj>
<Details ><![CDATA[No Pending transactions displayed]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:11]]></Time>
<TimeTick>1619583671</TimeTick>
<NodeArgs eType="User" icon="488" nRep="41" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[No Pending transactions exists]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:12]]></Time>
<TimeTick>1619583672</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Repair Payment.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:12]]></Time>
<TimeTick>1619583672</TimeTick>
<NodeArgs eType="Replay" icon="485" nRep="43" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Repair Payment.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="484" nRep="42" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[The repair table is displayed]]></Obj>
<Details ><![CDATA[Test Passed]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:12]]></Time>
<TimeTick>1619583672</TimeTick>
<NodeArgs eType="User" icon="488" nRep="44" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[The repair table is displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:24]]></Time>
<TimeTick>1619583684</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:24]]></Time>
<TimeTick>1619583684</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="46" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:24]]></Time>
<TimeTick>1619583684</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="48" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:28]]></Time>
<TimeTick>1619583688</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="50" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Back.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:48]]></Time>
<TimeTick>1619583708</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="52" >
<Disp><![CDATA[Back.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:48]]></Time>
<TimeTick>1619583708</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="53" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Log Off.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:48]]></Time>
<TimeTick>1619583708</TimeTick>
<NodeArgs eType="Replay" icon="486" nRep="55" >
<Disp><![CDATA[Log Off.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[4/28/2021 - 5:21:48]]></Time>
<TimeTick>1619583708</TimeTick>
<NodeArgs eType="General" icon="489" nRep="56" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="484" nRep="45" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/28/2021 - 5:20:21" eTime="4/28/2021 - 5:21:48" passed="5" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="482" nRep="8" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="481" nRep="7" status="Passed" >
<Disp><![CDATA[Repairs_Reg_06_8_RepairTable Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="4/28/2021 - 5:20:19" eTime="4/28/2021 - 5:21:48" passed="5" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="479" nRep="3" status="Warning" >
<Disp><![CDATA[Test Repairs_Reg_06_8_RepairTable Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>