<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2SIT919R2"><DocLocation><![CDATA[C:\Advanced Sales\Automation\Test Scripts\Recycle_TC_02]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Recycle_TC_02]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="915" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:18]]></Time>
<TimeTick>1619576838</TimeTick>
<NodeArgs eType="Replay" icon="918" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:18]]></Time>
<TimeTick>1619576838</TimeTick>
<NodeArgs eType="Replay" icon="918" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:22]]></Time>
<TimeTick>1619576842</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Main Menu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:22]]></Time>
<TimeTick>1619576842</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Main Menu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Log Off.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:25]]></Time>
<TimeTick>1619576845</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="14" >
<Disp><![CDATA[Log Off.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:25]]></Time>
<TimeTick>1619576845</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="15" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:25]]></Time>
<TimeTick>1619576845</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="17" >
<Disp><![CDATA[Back Office.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:25]]></Time>
<TimeTick>1619576845</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="19" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:25]]></Time>
<TimeTick>1619576845</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="21" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Back Office Login.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["5fad465bbaab8ecd3c73e570d644"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:25]]></Time>
<TimeTick>1619576845</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="23" >
<Disp><![CDATA[Back Office Login.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:25]]></Time>
<TimeTick>1619576845</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="25" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:31]]></Time>
<TimeTick>1619576851</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="27" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:33]]></Time>
<TimeTick>1619576853</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="28" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:33]]></Time>
<TimeTick>1619576853</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="30" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:35]]></Time>
<TimeTick>1619576855</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="31" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:35]]></Time>
<TimeTick>1619576855</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="33" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[DtvList.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#2"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:36]]></Time>
<TimeTick>1619576856</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="35" >
<Disp><![CDATA[DtvList.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[DtvList.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#6"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:38]]></Time>
<TimeTick>1619576858</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="37" >
<Disp><![CDATA[DtvList.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Adjustment Type.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Sellable"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:40]]></Time>
<TimeTick>1619576860</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="39" >
<Disp><![CDATA[Adjustment Type.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Reason.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["BUNDLE CREATE"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:42]]></Time>
<TimeTick>1619576862</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="41" >
<Disp><![CDATA[Reason.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Justification.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TESTING"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:44]]></Time>
<TimeTick>1619576864</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="43" >
<Disp><![CDATA[Justification.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:46]]></Time>
<TimeTick>1619576866</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="45" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Enter PLU.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6901443275137"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:48]]></Time>
<TimeTick>1619576868</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="47" >
<Disp><![CDATA[Enter PLU.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Enter Quantity.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:52]]></Time>
<TimeTick>1619576872</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="49" >
<Disp><![CDATA[Enter Quantity.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[IMEI/Serial Number.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["210000000001632"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:56]]></Time>
<TimeTick>1619576876</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="51" >
<Disp><![CDATA[IMEI/Serial Number.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Add.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:27:58]]></Time>
<TimeTick>1619576878</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="53" >
<Disp><![CDATA[Add.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:00]]></Time>
<TimeTick>1619576880</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="55" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:02]]></Time>
<TimeTick>1619576882</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="57" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Till.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:04]]></Time>
<TimeTick>1619576884</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="59" >
<Disp><![CDATA[Till.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Enter PLU or IMEI.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["6901443275137"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:06]]></Time>
<TimeTick>1619576886</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="61" >
<Disp><![CDATA[Enter PLU or IMEI.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:12]]></Time>
<TimeTick>1619576892</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="63" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:12]]></Time>
<TimeTick>1619576892</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="65" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Enter IMEI.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:14]]></Time>
<TimeTick>1619576894</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="66" >
<Disp><![CDATA[Enter IMEI.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Enter IMEI.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["210000000001632"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:14]]></Time>
<TimeTick>1619576894</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="68" >
<Disp><![CDATA[Enter IMEI.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[IMEI/Serial Number.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:18]]></Time>
<TimeTick>1619576898</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="70" >
<Disp><![CDATA[IMEI/Serial Number.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ 210000000001632 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["NEW"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:20]]></Time>
<TimeTick>1619576900</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="72" >
<Disp><![CDATA[[ 210000000001632 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Retrieve / Process.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:22]]></Time>
<TimeTick>1619576902</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="74" >
<Disp><![CDATA[Retrieve / Process.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Manual Sale.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:24]]></Time>
<TimeTick>1619576904</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="76" >
<Disp><![CDATA[Manual Sale.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ 210000000001632 ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["CR3-CONTINGENCY"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:26]]></Time>
<TimeTick>1619576906</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="78" >
<Disp><![CDATA[[ 210000000001632 ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ PosTextField ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["273890458"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:28]]></Time>
<TimeTick>1619576908</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="80" >
<Disp><![CDATA[[ PosTextField ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ PosTextField ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["5038262042976"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:32]]></Time>
<TimeTick>1619576912</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="82" >
<Disp><![CDATA[[ PosTextField ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ DtvComboBox ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["9000000268906 - 30D OUT S2 DD UNLTD   2GB £22"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:35]]></Time>
<TimeTick>1619576915</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="84" >
<Disp><![CDATA[[ DtvComboBox ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ DtvComboBox ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["9000000233225 - O2 INSURE A/DAMAGE £7.50"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:39]]></Time>
<TimeTick>1619576919</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="86" >
<Disp><![CDATA[[ DtvComboBox ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ IMEI Number ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["07777777777"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:41]]></Time>
<TimeTick>1619576921</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="88" >
<Disp><![CDATA[[ IMEI Number ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ SIM Number ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0012345678901"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:44]]></Time>
<TimeTick>1619576924</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="90" >
<Disp><![CDATA[[ SIM Number ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ icon-checkbox ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:47]]></Time>
<TimeTick>1619576927</TimeTick>
<NodeArgs eType="Replay" icon="923" nRep="92" >
<Disp><![CDATA[[ icon-checkbox ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ IMEI Number ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["210000000001640"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:49]]></Time>
<TimeTick>1619576929</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="94" >
<Disp><![CDATA[[ IMEI Number ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Get Recycle Credit Value.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:52]]></Time>
<TimeTick>1619576932</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="96" >
<Disp><![CDATA[Get Recycle Credit Value.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Device ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Mobile"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:54]]></Time>
<TimeTick>1619576934</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="98" >
<Disp><![CDATA[[ Device ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ Manufacturer ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:54]]></Time>
<TimeTick>1619576934</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="99" >
<Disp><![CDATA[[ Manufacturer ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Manufacturer ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["HUAWEI"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:54]]></Time>
<TimeTick>1619576934</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="101" >
<Disp><![CDATA[[ Manufacturer ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Model.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["P SMART 2019"]]></Details>
<Time><![CDATA[4/28/2021 - 3:28:58]]></Time>
<TimeTick>1619576938</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="103" >
<Disp><![CDATA[Model.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:00]]></Time>
<TimeTick>1619576940</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="105" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ e.g.Google Lock ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Yes"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:02]]></Time>
<TimeTick>1619576942</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="107" >
<Disp><![CDATA[[ e.g.Google Lock ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ e.g.Phone Network ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Vodafone"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:04]]></Time>
<TimeTick>1619576944</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="109" >
<Disp><![CDATA[[ e.g.Phone Network ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ e.g.fully functional ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Yes, but some of the buttons/cosmetic parts are missing"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:06]]></Time>
<TimeTick>1619576946</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="111" >
<Disp><![CDATA[[ e.g.fully functional ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Next.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:08]]></Time>
<TimeTick>1619576948</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="113" >
<Disp><![CDATA[Next.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ e.g.Physical Damage ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Yes, the casing is cracked/damaged and/or buttons/ports are damaged"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:10]]></Time>
<TimeTick>1619576950</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="115" >
<Disp><![CDATA[[ e.g.Physical Damage ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ e.g.water damaged ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Yes, but everything works as it should"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:12]]></Time>
<TimeTick>1619576952</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="117" >
<Disp><![CDATA[[ e.g.water damaged ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:14]]></Time>
<TimeTick>1619576954</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="119" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:16]]></Time>
<TimeTick>1619576956</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="121" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ IMEI Number ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SL14DX"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:18]]></Time>
<TimeTick>1619576958</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="123" >
<Disp><![CDATA[[ IMEI Number ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ Building Number ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["260"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:20]]></Time>
<TimeTick>1619576960</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="125" >
<Disp><![CDATA[[ Building Number ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:22]]></Time>
<TimeTick>1619576962</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="127" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:24]]></Time>
<TimeTick>1619576964</TimeTick>
<NodeArgs eType="Replay" icon="921" nRep="129" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Name.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Mr"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:26]]></Time>
<TimeTick>1619576966</TimeTick>
<NodeArgs eType="Replay" icon="920" nRep="131" >
<Disp><![CDATA[Name.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[PosTextField.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["T"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:28]]></Time>
<TimeTick>1619576968</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="133" >
<Disp><![CDATA[PosTextField.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ 210000000001632 ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Accepta"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:30]]></Time>
<TimeTick>1619576970</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="135" >
<Disp><![CDATA[[ 210000000001632 ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Contact Number.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0777777777"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:32]]></Time>
<TimeTick>1619576972</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="137" >
<Disp><![CDATA[Contact Number.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ Mobile Number ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["07665432154"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:34]]></Time>
<TimeTick>1619576974</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="139" >
<Disp><![CDATA[[ Mobile Number ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[Email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TEST@TELEFONICA.COM"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:36]]></Time>
<TimeTick>1619576976</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="141" >
<Disp><![CDATA[Email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[[ Confirm Email ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TEST@TELEFONICA.COM"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:38]]></Time>
<TimeTick>1619576978</TimeTick>
<NodeArgs eType="Replay" icon="922" nRep="143" >
<Disp><![CDATA[[ Confirm Email ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[[ icon-checkbox ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:40]]></Time>
<TimeTick>1619576980</TimeTick>
<NodeArgs eType="Replay" icon="923" nRep="145" >
<Disp><![CDATA[[ icon-checkbox ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[[ icon-checkbox ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[4/28/2021 - 3:29:42]]></Time>
<TimeTick>1619576982</TimeTick>
<NodeArgs eType="Replay" icon="923" nRep="147" >