<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2SIT919R2"><DocLocation><![CDATA[C:\Advanced Sales\Automation\Test Scripts\TC_03_AdvSalesOOTB_KeypadLogin]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[TC_03_AdvSalesOOTB_KeypadLogin]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="546" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj plainTxt="False" ><![CDATA[Add-in(s) not activated]]></Obj>
<Details plainTxt="False" ><![CDATA[The following add-in(s) were associated with your test, but are not currently loaded: 
Flex.]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:06]]></Time>
<TimeTick>1619583486</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="5" status="Warning" >
<Disp><![CDATA[Add-in(s) not activated]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:09]]></Time>
<TimeTick>1619583489</TimeTick>
<NodeArgs eType="Replay" icon="549" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point.Restore]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="550" nRep="12" >
<Disp><![CDATA[Oracle Retail Xstore Point.Restore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="14" >
<Disp><![CDATA[1.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[0.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="16" >
<Disp><![CDATA[0.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[0.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="18" >
<Disp><![CDATA[0.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Enter.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="20" >
<Disp><![CDATA[Enter.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="22" >
<Disp><![CDATA[1.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="24" >
<Disp><![CDATA[2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[3.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="26" >
<Disp><![CDATA[3.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[4.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="28" >
<Disp><![CDATA[4.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Enter.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:11]]></Time>
<TimeTick>1619583491</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="30" >
<Disp><![CDATA[Enter.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:14]]></Time>
<TimeTick>1619583494</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="32" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:16]]></Time>
<TimeTick>1619583496</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="34" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Hotkeys ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:18]]></Time>
<TimeTick>1619583498</TimeTick>
<NodeArgs eType="Replay" icon="551" nRep="35" >
<Disp><![CDATA[[ Hotkeys ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="550" nRep="11" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[Login to Till]]></Obj>
<Details ><![CDATA[Test step passed]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:18]]></Time>
<TimeTick>1619583498</TimeTick>
<NodeArgs eType="User" icon="552" nRep="36" status="Passed" >
<Disp><![CDATA[Login to Till]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[4/28/2021 - 5:18:20]]></Time>
<TimeTick>1619583500</TimeTick>
<NodeArgs eType="General" icon="553" nRep="37" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/28/2021 - 5:18:06" eTime="4/28/2021 - 5:18:20" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="548" nRep="8" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="547" nRep="7" status="Passed" >
<Disp><![CDATA[TC_03_AdvSalesOOTB_KeypadLogin Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="4/28/2021 - 5:18:05" eTime="4/28/2021 - 5:18:20" passed="2" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="545" nRep="3" status="Warning" >
<Disp><![CDATA[Test TC_03_AdvSalesOOTB_KeypadLogin Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>